### PR TITLE
ISSUE-176: adds ability for user to import a private key

### PR DESCRIPTION
**Pull request by ArtemBurakov**

### CODE REVIEW

**Comment by rileystephens28** [comment]
There is a bug causing the "Add Address" slide up modal to appear when clicking the top right address button which should only show the list of addresses. This occurred for me after I imported a few addresses from private key without recovering a wallet.


https://github.com/PelagusWallet/pelagus-extension/assets/24363438/be24d221-ffcb-403b-be1c-b13f6fb73453

**Comment by rileystephens28** [comment]
There is a bug that prevents wallet addresses from being added when the currently selected address is one that was imported from private key. There is no issue adding wallet addresses when the currently selected address in one from the a wallet.


https://github.com/PelagusWallet/pelagus-extension/assets/24363438/67cc60c8-35cc-414e-8e8b-b18eaece0dc1

**Comment by rileystephens28** [comment]
@ArtemBurakov can you rebase this branch on main so we can prepare it for merging?

**Comment by ArtemBurakov** [comment]
I have already resolved the conflicts. There are a few things to check. I am waiting on approve from @booleksandra

**Comment by ArtemBurakov** [comment]
@rileystephens28 , I've fixed the last bug and tested it myself. I'm confident that this specific bug won't occur. However, by the end of our working day, @booleksandra  can verify it as QA.

Here's how you can test it on your end:
1. Install and import/create a new wallet
2. Import an address via a private key
3. From the home view after the import, simply click on the account icon in the top right corner. Without making any changes/clicks to the accounts, click on the "+ Add Address" button and choose a shard. The shard should be successfully added to your wallet (previously, there was a bug where the new address wasn't being added)

**Review by rileystephens28 — DISMISSED** [review]

**Comment by rileystephens28** [comment]
Closing this PR since the rebased version of this feature was open in #228

**Pull request closed without merging**
